databases:
  - name: budget_app
    databaseName: budget_app
    user: amos

services:
  - type: web
    name: budget_app
    runtime: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mySite
          property: connectingString
      - key: RAILS_MASTER_KEY
    sync: false
